=== dvaneynde/home-automation/DiamondBoardsConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://dlvmechanografie.eu/DiamondBoardsConfig"
	xmlns:tns="http://dlvmechanografie.eu/DiamondBoardsConfig"
	elementFormDefault="qualified">

	<element name="boards">
		<complexType>
			<sequence minOccurs="1" maxOccurs="unbounded">
				<choice>
					<element name="opalmm" type="tns:opalmmType" />
					<element name="dmmat" type="tns:dmmatType" />
					<element name="opmm1616" type="tns:opmm1616Type" />
				</choice>
			</sequence>
		</complexType>
	</element>

	<complexType name="boardStruct" abstract="true">
		<attribute name="board" type="int" use="required" />
		<attribute name="address" type="string" use="required" />
		<attribute name="desc" type="string" />
	</complexType>
	<complexType name="boardChannelStruct">
		<attribute name="channel" type="int" use="required" />
		<attribute name="logical-id" type="string" use="optional" />
	</complexType>
	<complexType name="channel0to7Struct">
		<sequence minOccurs="1" maxOccurs="8">
			<element name="channel" type="tns:boardChannelStruct" />
		</sequence>
	</complexType>
	<complexType name="channel0to15Struct">
		<sequence minOccurs="1" maxOccurs="16">
			<element name="channel" type="tns:boardChannelStruct" />
		</sequence>
	</complexType>
	<complexType name="channel0to1Struct">
		<sequence minOccurs="1" maxOccurs="2">
			<element name="channel" type="tns:boardChannelStruct" />
		</sequence>
	</complexType>

	<complexType name="opalmmType">
		<complexContent>
			<extension base="tns:boardStruct">
				<sequence>
					<element name="digital-input" type="tns:channel0to7Struct"
						minOccurs="0" />
					<element name="digital-output" type="tns:channel0to7Struct"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="opmm1616Type">
		<complexContent>
			<extension base="tns:boardStruct">
				<sequence>
					<element name="digital-input" type="tns:channel0to15Struct"
						minOccurs="0" />
					<element name="digital-output" type="tns:channel0to15Struct"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
	<complexType name="dmmatType">
		<complexContent>
			<extension base="tns:boardStruct">
				<sequence>
					<element name="analog-input" type="tns:channel0to1Struct"
						minOccurs="0" />
					<element name="analog-output" type="tns:channel0to1Struct"
						minOccurs="0" />
					<element name="digital-input" type="tns:channel0to7Struct"
						minOccurs="0" />
					<element name="digital-output" type="tns:channel0to7Struct"
						minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>
</schema>

=== dvaneynde/home-automation/src/test/resources/TestDiamondHwConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<boards xmlns="http://dlvmechanografie.eu/DiamondBoardsConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dlvmechanografie.eu/DiamondBoardsConfig ../../main/resources/DiamondBoardsConfig.xsd ">
	<dmmat board="0" address="0x330" desc="Board 0, dmmatt.">
		<analog-input>
			<channel channel="0" logical-id="AnalogIn" />
		</analog-input>
		<analog-output>
			<channel channel="0" logical-id="LichtVeranda" />
			<channel channel="1" logical-id="LichtCircanteRondom" />
		</analog-output>
		<digital-input>
			<channel channel="0" logical-id="SchakLichtKeuken" />
			<channel channel="1" logical-id="SchakScreenKeukenDown" />
			<channel channel="2" logical-id="SchakScreenKeukenUp" />
			<channel channel="3" logical-id="SchakLichtBadk0" />
			<channel channel="4" logical-id="SchakVentilatorBadk0" />
			<channel channel="5" logical-id="SchakScreenZuidUp" />
			<channel channel="6" logical-id="SchakScreenZuidDown" />
			<channel channel="7" logical-id="SchakSlaapZuidWand" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="LichtBureau" />
			<channel channel="1" logical-id="LichtCircante" />
			<channel channel="2" logical-id="LichtInkom" />
			<channel channel="3" logical-id="VentilatorWC0" />
			<channel channel="4" logical-id="LichtWC0" />
			<channel channel="5" logical-id="VentilatorBadk0" />
			<channel channel="6" logical-id="LichtBadk1" />
			<channel channel="7" logical-id="LichtBadk0" />
		</digital-output>
	</dmmat>
	<dmmat board="1" address="0x300" desc="Board 1, dmmatt.">
		<analog-output>
			<channel channel="0" logical-id="LichtZithoek" />
			<channel channel="1" />
		</analog-output>
		<digital-input>
			<channel channel="0" logical-id="Windmeter" />
			<channel channel="7" logical-id="SchakBuitenTuin" />
		</digital-input>
	</dmmat>
	<opmm1616 board="2" address="0x200" desc="Board 2, opmm1616.">
		<digital-input>
			<channel channel="0" logical-id="SchakLichtVerandaDown" />
			<channel channel="1" logical-id="SchakLichtVerandaUp" />
			<channel channel="2" logical-id="SchakScreenLangDown" />
			<channel channel="3" logical-id="SchakScreenLangUp" />
			<channel channel="4" logical-id="SchakScreenBreedDown" />
			<channel channel="5" logical-id="SchakScreenBreedUp" />
			<channel channel="6" logical-id="SchakScreenAllDown" />
			<channel channel="7" logical-id="SchakScreenAllUp" />
			<channel channel="8" logical-id="SchakVentilatorWC0" />
			<channel channel="9" logical-id="SchakLichtBureau" />
			<channel channel="10" logical-id="SchakLichtZithoekDown" />
			<channel channel="11" logical-id="SchakLichtZithoekUp" />
			<channel channel="12" logical-id="SchakLichtCircanteRondomDown" />
			<channel channel="13" logical-id="SchakLichtCircanteRondomUp" />
			<channel channel="14" logical-id="SchakLichtCircante" />
			<channel channel="15" logical-id="SchakLichtInkom" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="ScreenSlaapNoordDown" />
			<channel channel="1" logical-id="LichtGangBoven" />
			<channel channel="2" logical-id="LichtSlaapZuidSpots" />
			<!-- LichtSlaapZuidWand aansluiting is weggestopt achter pleister -->
			<channel channel="3" logical-id="LichtSlaapZuidWand" /> 
			<channel channel="4" logical-id="LichtSlaapZuidwestSpots" />
			<channel channel="5" logical-id="LichtSlaapZuidwestWand" />
			<channel channel="6" logical-id="LichtSlaapNoordSpots" />
			<channel channel="7" logical-id="LichtSlaapNoordWand" />
			<channel channel="8" logical-id="LichtKeuken" />
			<channel channel="9" logical-id="LichtGaragePoort" />
			<channel channel="10" logical-id="LichtGarageTuin" />
			<channel channel="11" logical-id="ScreenLangUp" />
			<channel channel="12" logical-id="ScreenLangDown" />
			<channel channel="13" logical-id="ScreenBreedUp" />
			<channel channel="14" logical-id="ScreenBreedDown" />
			<channel channel="15" logical-id="ScreenKeukenDown" />
		</digital-output>
	</opmm1616>
	<opalmm board="3" address="0x240" desc="Board 3, opalmm 8.">
		<digital-input>
			<channel channel="0" logical-id="SchakScreenZuidwestTuinDown" />
			<channel channel="1" logical-id="SchakScreenZuidwestTuinUp" />
			<channel channel="2" logical-id="SchakScreenZuidwestOpzijDown" />
			<channel channel="3" logical-id="SchakScreenZuidwestOpzijUp" />
			<channel channel="4" logical-id="SchakSlaapNoordWand" />
			<channel channel="5" logical-id="SchakSlaapNoordSpots" />
			<channel channel="6" logical-id="SchakSlaapZuidSpots" />
			<channel channel="7" logical-id="SchakLichtWC0" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="LichtNacht" />
			<channel channel="1" logical-id="IndicLichtNacht" /><!-- indicator licht nacht -->
			<channel channel="2" logical-id="LichtTerras" />
			<channel channel="3" logical-id="IndicScreenAuto" /><!-- tobe indicator screen-automaat aan/uit -->
			<channel channel="4" logical-id="StopkBuiten" />
			<channel channel="5" logical-id="IndicWindZon" /><!-- tobe indicator zon(aan) / teveel-wind(knipperen) bij automaat aan -->
			<channel channel="6" logical-id="StopkCarport" />
			<channel channel="7" /><!-- TODO domotica functioneert, lampje in kast -->
		</digital-output>
	</opalmm>
	<opalmm board="4" address="0x280" desc="Board 4, opalmm 8.">
		<digital-input>
			<channel channel="0" logical-id="SchakLichtGaragePoort" />
			<channel channel="1" logical-id="SchakLichtGarageTuin" />
			<channel channel="2" logical-id="SchakLichtBadk1" />
			<channel channel="3" logical-id="SchakSlaapZuidwestSpots" />
			<channel channel="4" logical-id="SchakSlaapZuidwestWand" />
			<channel channel="5" logical-id="SchakLichtGangBoven" />
			<channel channel="6" logical-id="SchakScreenSlaapNoordDown" />
			<channel channel="7" logical-id="SchakScreenSlaapNoordUp" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="ScreenSlaapNoordUp" />
			<channel channel="1" logical-id="ScreenZuidwestOpzijDown" />
			<channel channel="2" logical-id="ScreenZuidwestOpzijUp" />
			<channel channel="3" logical-id="ScreenZuidwestTuinUp" />
			<channel channel="4" logical-id="ScreenZuidwestTuinDown" />
			<channel channel="5" logical-id="ScreenZuidDown" />
			<channel channel="6" logical-id="ScreenZuidUp" />
			<channel channel="7" logical-id="ScreenKeukenUp" />
		</digital-output>
	</opalmm>
</boards>

=== dvaneynde/home-automation/src/test/resources/TestDiamondHwConfig1.xml
<?xml version="1.0" encoding="UTF-8"?>
<boards xmlns="http://dlvmechanografie.eu/DiamondBoardsConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dlvmechanografie.eu/DiamondBoardsConfig ../../main/resources/DiamondBoardsConfig.xsd ">
	<opalmm address="0x380" board="0" desc="Een opalmm bordje.">
		<digital-input>
			<channel channel="5" logical-id="87" />
		</digital-input>
		<digital-output>
			<channel channel="2" logical-id="13" />
		</digital-output>
	</opalmm>
	<dmmat board="1" address="0x400" desc="First dmmatt board">
		<analog-output>
			<channel channel="0" logical-id="10" />
		</analog-output>
	</dmmat>
	<opmm1616 board="2" address="0x410" desc="Third board, opmm1616">
		<digital-input>
			<channel channel="5" logical-id="100" />
			<channel channel="6" logical-id="101" />
			<channel channel="7" logical-id="102" />
			<channel channel="8" logical-id="103" />
			<channel channel="9" logical-id="104" />
			<channel channel="10" logical-id="105" />
			<channel channel="11" logical-id="106" />
			<channel channel="12" logical-id="107" />
			<channel channel="13" logical-id="108" />
			<channel channel="14" logical-id="109" />
			<channel channel="0" logical-id="110" />
			<channel channel="15" logical-id="111" />
		</digital-input>
		<digital-output>
			<channel channel="2" logical-id="120" />
		</digital-output>
	</opmm1616>

</boards>

=== dvaneynde/home-automation/DiamondBoardsConfig.xml
<?xml version="1.0" encoding="UTF-8"?>
<boards xmlns="http://dlvmechanografie.eu/DiamondBoardsConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dlvmechanografie.eu/DiamondBoardsConfig DiamondBoardsConfig.xsd ">
	<dmmat board="0" address="0x330" desc="Board 0, dmmatt.">
		<analog-input>
			<channel channel="0" logical-id="AnalogIn" />
		</analog-input>
		<analog-output>
			<channel channel="0" logical-id="LichtVeranda" />
			<channel channel="1" logical-id="LichtCircanteRondom" />
		</analog-output>
		<digital-input>
			<channel channel="0" logical-id="SchakLichtKeuken" />
			<channel channel="1" logical-id="SchakScreenKeukenDown" />
			<channel channel="2" logical-id="SchakScreenKeukenUp" />
			<channel channel="3" logical-id="SchakLichtBadk0" />
			<channel channel="4" logical-id="SchakVentilatorBadk0" />
			<channel channel="5" logical-id="SchakScreenTomasUp" />
			<channel channel="6" logical-id="SchakScreenTomasDown" />
			<channel channel="7" logical-id="SchakLichtTomasWand" /><!-- TODO Was SchakLichtTomas, bedoeld spots, maar bleek andersom -->
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="LichtBureau" />
			<channel channel="1" logical-id="LichtCircante" />
			<channel channel="2" logical-id="LichtInkom" />
			<channel channel="3" logical-id="VentilatorWC0" />
			<channel channel="4" logical-id="LichtWC0" />
			<channel channel="5" logical-id="VentilatorBadk0" />
			<channel channel="6" logical-id="LichtBadk1" />
			<channel channel="7" logical-id="LichtBadk0" />
		</digital-output>
	</dmmat>
	<dmmat board="1" address="0x300" desc="Board 1, dmmatt.">
		<analog-output>
			<channel channel="0" logical-id="LichtZithoek" />
			<channel channel="1" />
		</analog-output>
		<digital-input>
			<channel channel="0" logical-id="Windmeter" />
			<channel channel="7" logical-id="SchakBuitenTuin" />
		</digital-input>
	</dmmat>
	<opmm1616 board="2" address="0x200" desc="Board 2, opmm1616.">
		<digital-input>
			<channel channel="0" logical-id="SchakLichtVerandaDown" />
			<channel channel="1" logical-id="SchakLichtVerandaUp" />
			<channel channel="2" logical-id="SchakScreenLangDown" />
			<channel channel="3" logical-id="SchakScreenLangUp" />
			<channel channel="4" logical-id="SchakScreenBreedDown" />
			<channel channel="5" logical-id="SchakScreenBreedUp" />
			<channel channel="6" logical-id="SchakScreenAllDown" />
			<channel channel="7" logical-id="SchakScreenAllUp" />
			<channel channel="8" logical-id="SchakVentilatorWC0" />
			<channel channel="9" logical-id="SchakLichtBureau" />
			<channel channel="10" logical-id="SchakLichtZithoekDown" />
			<channel channel="11" logical-id="SchakLichtZithoekUp" />
			<channel channel="12" logical-id="SchakLichtCircanteRondomDown" />
			<channel channel="13" logical-id="SchakLichtCircanteRondomUp" />
			<channel channel="14" logical-id="SchakLichtCircante" />
			<channel channel="15" logical-id="SchakLichtInkom" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="ScreenRoosDown" />
			<channel channel="1" logical-id="LichtGangBoven" />
			<channel channel="2" logical-id="LichtTomasSpots" />
			<channel channel="3" logical-id="LichtTomasWand" />
			<channel channel="4" logical-id="LichtDries" />
			<channel channel="5" logical-id="LichtDriesWand" />
			<channel channel="6" logical-id="LichtRoos" />
			<channel channel="7" logical-id="LichtRoosWand" />
			<channel channel="8" logical-id="LichtKeuken" />
			<channel channel="9" logical-id="LichtGaragePoort" />
			<channel channel="10" logical-id="LichtGarageTuin" />
			<channel channel="11" logical-id="ScreenLangUp" />
			<channel channel="12" logical-id="ScreenLangDown" />
			<channel channel="13" logical-id="ScreenBreedUp" />
			<channel channel="14" logical-id="ScreenBreedDown" />
			<channel channel="15" logical-id="ScreenKeukenDown" />
		</digital-output>
	</opmm1616>
	<opalmm board="3" address="0x240" desc="Board 3, opalmm 8.">
		<digital-input>
			<channel channel="0" logical-id="SchakScreenDriesTuinDown" />
			<channel channel="1" logical-id="SchakScreenDriesTuinUp" />
			<channel channel="2" logical-id="SchakScreenDriesOpzijDown" />
			<channel channel="3" logical-id="SchakScreenDriesOpzijUp" />
			<channel channel="4" logical-id="SchakLichtRoosWand" />
			<channel channel="5" logical-id="SchakLichtRoos" />
			<channel channel="6" logical-id="SchakLichtTomasSpots" /><!-- TODO Was: SchakLichtTomasWand; check kabel -->
			<channel channel="7" logical-id="SchakLichtWC0" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="LichtNacht" />
			<channel channel="1" logical-id="IndicLichtNacht" /><!-- indicator licht nacht -->
			<channel channel="2" logical-id="LichtTerras" />
			<channel channel="3" logical-id="IndicScreenAuto" /><!-- tobe indicator screen-automaat aan/uit -->
			<channel channel="4" logical-id="StopkBuiten" />
			<channel channel="5" logical-id="IndicWindZon" /><!-- tobe indicator zon(aan) / teveel-wind(knipperen) bij automaat aan -->
			<channel channel="6" logical-id="StopkCarport" />
			<channel channel="7" /><!-- TODO domotica functioneert, lampje in kast -->
		</digital-output>
	</opalmm>
	<opalmm board="4" address="0x280" desc="Board 4, opalmm 8.">
		<digital-input>
			<channel channel="0" logical-id="SchakLichtGaragePoort" />
			<channel channel="1" logical-id="SchakLichtGarageTuin" />
			<channel channel="2" logical-id="SchakLichtBadk1" />
			<channel channel="3" logical-id="SchakLichtDries" />
			<channel channel="4" logical-id="SchakLichtDriesWand" />
			<channel channel="5" logical-id="SchakLichtGangBoven" />
			<channel channel="6" logical-id="SchakScreenRoosDown" />
			<channel channel="7" logical-id="SchakScreenRoosUp" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="ScreenRoosUp" />
			<channel channel="1" logical-id="ScreenDriesOpzijDown" />
			<channel channel="2" logical-id="ScreenDriesOpzijUp" />
			<channel channel="3" logical-id="ScreenDriesTuinUp" />
			<channel channel="4" logical-id="ScreenDriesTuinDown" />
			<channel channel="5" logical-id="ScreenTomasDown" />
			<channel channel="6" logical-id="ScreenTomasUp" />
			<channel channel="7" logical-id="ScreenKeukenUp" />
		</digital-output>
	</opalmm>
</boards>

=== dvaneynde/home-automation/src/test/resources/TestDiamondHwConfig2.xml
<?xml version="1.0" encoding="UTF-8"?>
<boards xmlns="http://dlvmechanografie.eu/DiamondBoardsConfig"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dlvmechanografie.eu/DiamondBoardsConfig ../../main/resources/DiamondBoardsConfig.xsd ">
	<opalmm board="0" address="0x300" desc="OPALMM 0 - enkel output.">
		<digital-output>
			<channel channel="2" logical-id="0" />
		</digital-output>
	</opalmm>
	<opalmm board="1" address="0x310" desc="OPALMM 1 - enkel input">
		<digital-input>
			<channel channel="5" logical-id="1" />
		</digital-input>
	</opalmm>
	<dmmat board="2" address="0x400"
		desc="DMMAT 1 - analog input enkel channel 0, analog output beide kanalen.">
		<analog-input>
			<channel channel="0" logical-id="10" />
		</analog-input>
		<analog-output>
			<channel channel="0" logical-id="11" />
			<channel channel="1" logical-id="12" />
		</analog-output>
	</dmmat>
	<dmmat board="3" address="0x410"
		desc="DMMAT 2 - analog output enkel channel 1; digitaal in en uit.">
		<analog-output>
			<channel channel="1" logical-id="30" />
		</analog-output>
		<digital-input>
			<channel channel="0" logical-id="31" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="32" />
			<channel channel="7" logical-id="33" />
		</digital-output>
	</dmmat>
	<dmmat board="4" address="0x420"
		desc="DMMAT 2 - analog input enkel channel 1, output beide kanalen; digitaal in en uit.">
		<analog-input>
			<channel channel="1" logical-id="20" />
		</analog-input>
		<analog-output>
			<channel channel="0" logical-id="21" />
			<channel channel="1" logical-id="22" />
		</analog-output>
		<digital-input>
			<channel channel="0" logical-id="23" />
		</digital-input>
		<digital-output>
			<channel channel="0" logical-id="24" />
			<channel channel="5" logical-id="25" />
		</digital-output>
	</dmmat>
</boards>
